apiversion: v1
kind: AppConfig
spec:
  db:
    path: ./db
  jwt:
    key: wfhrmbwzs8fyhuxybce3zcz9o42ks8ir
  server:
    bind:
      host: 0.0.0.0
      port: 30028
    ssl:
      enable: false
  session:
    expires: 24
